# Generated by Django 3.2 on 2021-07-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=1000)),
                ('controlller_name', models.CharField(max_length=1000)),
                ('fa_icon', models.CharField(max_length=500)),
                ('operations', models.CharField(max_length=1000)),
            ],
        ),
    ]
