# Generated by Django 3.2.4 on 2021-07-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='general_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField(null=True)),
                ('code', models.CharField(max_length=200, null=True)),
                ('key_value', models.CharField(max_length=200, null=True)),
                ('vale', models.CharField(max_length=5000, null=True)),
                ('serilize', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
