# Generated by Django 3.2.5 on 2021-08-27 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_auto_20210822_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='controller_name',
        ),
        migrations.RemoveField(
            model_name='module',
            name='fa_icon',
        ),
    ]
