# Generated by Django 3.2.5 on 2021-07-31 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_general_settings'),
        ('admin_dashboard', '0002_module'),
    ]

    operations = [
    ]
