# Generated by Django 3.2.5 on 2021-08-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_auto_20210827_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='export',
            field=models.BooleanField(default=False),
        ),
    ]
