# Generated by Django 3.2 on 2021-08-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_merge_0002_general_settings_0002_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='general_setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='Favicon/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='Logo/')),
                ('Application_Name', models.CharField(max_length=500)),
                ('timezone', models.CharField(max_length=100)),
                ('Default_language', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='general_settings',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
