# Generated by Django 3.2.4 on 2021-08-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0004_auto_20210811_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_from', models.CharField(max_length=100)),
                ('smtp_host', models.CharField(max_length=100)),
                ('smtp_port', models.CharField(max_length=100)),
                ('smtp_user', models.CharField(max_length=100)),
                ('smtp_pass', models.CharField(max_length=100)),
            ],
        ),
    ]
