# Generated by Django 3.2 on 2021-07-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_myuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='status',
            field=models.BooleanField(blank=True, max_length=30),
        ),
    ]
