# Generated by Django 3.2.4 on 2021-08-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0006_rename_emailsettings_email_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='recaptcha_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recaptcha_site_key', models.CharField(max_length=100)),
                ('recaptcha_secret_key', models.CharField(max_length=100)),
                ('recaptcha_lang', models.CharField(max_length=100)),
            ],
        ),
    ]
