# Generated by Django 3.2 on 2021-07-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0006_alter_myuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='Role',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='status',
            field=models.BooleanField(blank=True, max_length=30, null=True),
        ),
    ]
