# Generated by Django 3.2.5 on 2021-08-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0007_recaptcha_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='crud',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='log',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='profile',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='module',
            name='roles_permissions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='settings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
