# Generated by Django 3.2.5 on 2021-08-19 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0008_auto_20210819_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='operations',
        ),
    ]
